/* Installable, offline Study Vault: the build publishes each notes file under data/sheets/ and writes
   sw.js, a service worker that precaches the whole app. Its VERSION is a hash of every precached file,
   so each rebuild that changes anything ships a new worker and installed copies update on next launch. */
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";

/* Published copy of a notes file: the source exactly, plus a small fixed link back to the Vault
   (an installed app has no address bar). The notes content is not touched. */
export function publishSheet(html, outFile) {
  const back = '<a href="../../index.html" style="position:fixed;left:16px;bottom:16px;z-index:70;font:600 13px system-ui,sans-serif;' +
    'padding:7px 11px;border-radius:6px;background:#1A1C20;color:#FAF9F6;text-decoration:none;box-shadow:0 2px 8px rgba(0,0,0,.2)">← Study Vault</a>';
  const out = html.replace(/<body([^>]*)>/i, m => m + "\n" + back);
  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(outFile, out);
}

const walk = (dir, root) => fs.existsSync(dir) ? fs.readdirSync(dir, { withFileTypes: true }).flatMap(d =>
  d.isDirectory() ? walk(path.join(dir, d.name), root) : [path.relative(root, path.join(dir, d.name)).split(path.sep).join("/")]) : [];

export function writeServiceWorker(ROOT) {
  const files = ["index.html", "manifest.webmanifest",
    ...walk(path.join(ROOT, "app"), ROOT),
    ...walk(path.join(ROOT, "data"), ROOT).filter(f => f !== "data/registry.json")].filter(f => fs.existsSync(path.join(ROOT, f))).sort();
  const hash = crypto.createHash("sha256");
  files.forEach(f => hash.update(f).update(fs.readFileSync(path.join(ROOT, f))));
  const VERSION = "vault-" + hash.digest("hex").slice(0, 12);
  const sw = `/* Generated by tools/build.mjs — do not edit; rebuild instead. */
const VERSION = ${JSON.stringify(VERSION)};
const FONTS = "vault-fonts";
const PRECACHE = ${JSON.stringify(["./", ...files], null, 1)};
/* on a dev host, prefer the network so edits show up; everywhere else serve the precache (works offline) */
const LOCAL = /^(localhost|127\\.0\\.0\\.1|\\[::1\\])$/.test(location.hostname);

self.addEventListener("install", e => {
  e.waitUntil(caches.open(VERSION).then(c => c.addAll(PRECACHE.map(u => new Request(u, { cache: "reload" })))).then(() => self.skipWaiting()));
});
self.addEventListener("activate", e => {
  e.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k !== VERSION && k !== FONTS).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});
self.addEventListener("fetch", e => {
  const req = e.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin === location.origin) {
    const cached = () => caches.match(req, { ignoreSearch: true }).then(r => r || (req.mode === "navigate" ? caches.match("index.html") : undefined));
    e.respondWith(LOCAL
      ? fetch(req).catch(cached)
      : cached().then(r => r || fetch(req)));
  } else if (/(^|\\.)fonts\\.(googleapis|gstatic)\\.com$/.test(url.hostname)) {
    /* web fonts: stale-while-revalidate; the app falls back to system fonts without them */
    e.respondWith(caches.open(FONTS).then(async c => {
      const hit = await c.match(req);
      const net = fetch(req).then(r => { if (r.ok || r.type === "opaque") c.put(req, r.clone()); return r; }).catch(() => hit);
      return hit || net;
    }));
  }
});
`;
  fs.writeFileSync(path.join(ROOT, "sw.js"), sw);
  return { VERSION, files: files.length };
}
