/* Generated by tools/build.mjs — do not edit; rebuild instead. */
const VERSION = "vault-2c3cdc078221";
const FONTS = "vault-fonts";
const PRECACHE = [
 "./",
 "app/css/v2.css",
 "app/css/vault.css",
 "app/icons/apple-touch-icon.png",
 "app/icons/icon-192.png",
 "app/icons/icon-512.png",
 "app/icons/icon-maskable-512.png",
 "app/js/app.js",
 "app/js/content.js",
 "app/js/markup.js",
 "app/js/render.js",
 "app/js/store.js",
 "app/js/util.js",
 "app/js/v2/components/presentation.js",
 "app/js/v2/model/contracts.js",
 "app/js/v2/model/mock-data.js",
 "app/js/v2/views/prototype.js",
 "app/js/views/insight.js",
 "app/js/views/pages.js",
 "app/js/views/reader.js",
 "app/js/views/study.js",
 "data/manifest.js",
 "data/sheets/environment-and-ecology.html",
 "data/sheets/geography.html",
 "data/sheets/polity.html",
 "data/subjects/environment-and-ecology.js",
 "data/subjects/geography.js",
 "data/subjects/polity.js",
 "index.html",
 "manifest.webmanifest"
];
/* on a dev host, prefer the network so edits show up; everywhere else serve the precache (works offline) */
const LOCAL = /^(localhost|127\.0\.0\.1|\[::1\])$/.test(location.hostname);

self.addEventListener("install", e => {
  e.waitUntil(caches.open(VERSION).then(c => c.addAll(PRECACHE.map(u => new Request(u, { cache: "reload" })))).then(() => self.skipWaiting()));
});
self.addEventListener("activate", e => {
  e.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k !== VERSION && k !== FONTS).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});
self.addEventListener("fetch", e => {
  const req = e.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin === location.origin) {
    const cached = () => caches.match(req, { ignoreSearch: true }).then(r => r || (req.mode === "navigate" ? caches.match("index.html") : undefined));
    e.respondWith(LOCAL
      ? fetch(req).catch(cached)
      : cached().then(r => r || fetch(req)));
  } else if (/(^|\.)fonts\.(googleapis|gstatic)\.com$/.test(url.hostname)) {
    /* web fonts: stale-while-revalidate; the app falls back to system fonts without them */
    e.respondWith(caches.open(FONTS).then(async c => {
      const hit = await c.match(req);
      const net = fetch(req).then(r => { if (r.ok || r.type === "opaque") c.put(req, r.clone()); return r; }).catch(() => hit);
      return hit || net;
    }));
  }
});
